// src/lib/export-csv.ts
// Export client document data as CSV for QuickBooks, Excel, and other tools.
// Produces clean CSV that opens directly in Excel/Google Sheets and imports into QuickBooks.

import type { RequirementWithUploads } from '@/types'
import { formatDocType } from '@/lib/utils'
import { formatPeriod } from '@/lib/utils'

interface ExportRow {
  date: string
  description: string
  category: string
  status: string
  filename: string
  file_size: string
}

/** Export a client's monthly document status as CSV */
export function exportMonthCSV(
  businessName: string,
  requirements: RequirementWithUploads[],
  year: number,
  month: number,
): void {
  const period = formatPeriod(year, month)

  const rows: ExportRow[] = requirements.map(req => {
    const upload = req.uploads[0] // latest upload
    return {
      date: upload ? new Date(upload.uploaded_at).toLocaleDateString('en-US') : '',
      description: req.label,
      category: formatDocType(req.doc_type),
      status: upload ? 'Received' : req.required ? 'Missing' : 'Optional — Not Submitted',
      filename: upload?.filename_original ?? '',
      file_size: upload ? `${Math.round(upload.file_size_bytes / 1024)} KB` : '',
    }
  })

  const headers = ['Date Received', 'Document Description', 'Category', 'Status', 'Filename', 'File Size']
  const csvLines = [
    `# ${businessName} — Document Collection Report — ${period}`,
    `# Generated by BookDrop on ${new Date().toLocaleDateString('en-US')}`,
    '',
    headers.join(','),
    ...rows.map(row =>
      [row.date, csvEscape(row.description), row.category, row.status, csvEscape(row.filename), row.file_size].join(',')
    ),
    '',
    `# Summary: ${rows.filter(r => r.status === 'Received').length} received, ${rows.filter(r => r.status === 'Missing').length} missing`,
  ]

  const csv = csvLines.join('\r\n')
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8' }) // BOM for Excel
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${businessName.replace(/\s+/g, '_')}_${year}_${String(month).padStart(2, '0')}.csv`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/** Export as QuickBooks-compatible IIF format */
export function exportQuickBooksIIF(
  businessName: string,
  requirements: RequirementWithUploads[],
  year: number,
  month: number,
): void {
  const received = requirements.filter(r => r.uploads.length > 0)

  const lines = [
    '!TRNS\tTRNSID\tTRNSTYPE\tDATE\tACCNT\tNAME\tMEMO\tAMOUNT',
    '!SPL\tSPLID\tTRNSTYPE\tDATE\tACCNT\tNAME\tMEMO\tAMOUNT',
    '!ENDTRNS',
    ...received.map((req, i) => {
      const upload = req.uploads[0]
      const date = new Date(upload.uploaded_at).toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' })
      return [
        `TRNS\t${i + 1}\tGENERAL\t${date}\tDocuments Received\t${businessName}\t${req.label}\t0.00`,
        `SPL\t${i + 1}\tGENERAL\t${date}\tDocuments Received\t${businessName}\t${req.label}\t0.00`,
        'ENDTRNS',
      ].join('\r\n')
    }),
  ]

  const iif = lines.join('\r\n')
  const blob = new Blob([iif], { type: 'application/octet-stream' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${businessName.replace(/\s+/g, '_')}_${year}_${String(month).padStart(2, '0')}.iif`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/** Copy a Teams/Slack-friendly summary to clipboard */
export function copyTeamsSummary(
  businessName: string,
  requirements: RequirementWithUploads[],
  year: number,
  month: number,
): string {
  const period = formatPeriod(year, month)
  const received = requirements.filter(r => r.uploads.length > 0)
  const missing = requirements.filter(r => r.required && r.uploads.length === 0)

  const lines = [
    `**${businessName} — ${period} Document Status**`,
    '',
    `Received: ${received.length}/${requirements.length}`,
    ...received.map(r => `  - ${r.label} (${formatDocType(r.doc_type)})`),
    '',
    ...(missing.length > 0
      ? [`Missing (${missing.length}):`, ...missing.map(r => `  - ${r.label}`)]
      : ['All required documents received.']),
  ]

  const summary = lines.join('\n')
  navigator.clipboard.writeText(summary)
  return summary
}

function csvEscape(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}
